### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by crouti** [ANEX-Agency/gravityforms-phone-extension#3]
Extension installed and activated, but no change in public / admin telephone fields, something else to activate ?

**Comment by JoeHana** [comment]
You need to enable HTML5 Output in the Gravity Forms settings - WP-Admin >Forms > Settings > Output HTML5

**Comment by crouti** [comment]
Thanks!

**Comment by otaviobonder** [comment]
Hi, I activated the plugin, enabled HTML5 output, purged cache, but nothing happens. Any clue?

Edit: on my test form it worked perfectly, but not on my true form. Why is that?

Edit 2: I've discovered that it just work if it's on the first page of the form. My form is AJAX, and if I put the field to the second page it doesn't work

**Comment by JoeHana** [comment]
@otaviobps well, unfortunately I do not have enough time yet, but I guess this is because the required js and css doesn't get loaded after the ajax call? As far as I know there must be an action hook provided from gforms which "listens" to when a multipage form gets processed. You might need to look this up yourself and modify the code a little bit. Like in class-gf-phone-extension.php:130 you'd add something like add_action( 'gforms_ajax_tabbed_action_hook_name_you_need_to_lookup', array( $this, 'assets' ) ); in order to get the JS and CSS properly loaded on switching.

Let me know the outcome so I can update it.
